{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"authorship_tag":"ABX9TyPUrHBCS2oU4j7dBonqbtQy"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"markdown","source":["#Sentencia break\n","\n","###Descripción de la actividad.\n","\n","Observa el código y busca comprender qué sucedió en este caso:\n","\n","    x = 5\n","\n","    while True:\n","    \n","        x -= 1\n","        \n","        print(x)\n","        \n","        if x == 0:\n","            \n","            break\n","        \n","        print(\"Fin del bucle\")\n"],"metadata":{"id":"SopR1_QK7ae_"}},{"cell_type":"markdown","source":["- Lo que sucede es que el while es verdadero y entra, resta 1 a **x** y lo muestra. Y la condición de fin del bucle es cuando **x = 0**.\n","- Pero el \"error\" está en que cuando se resta 1 a x, muestra también el **print(\"Fin del bucle\")**, cuando no sucedió aún el fin de ciclo, se da por un error de identación."],"metadata":{"id":"wvjuVuhi-HPN"}}]}